apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  labels:
    app: catalogue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalogue
  template:
    metadata:
      labels:
        app: catalogue
    spec:
      containers:
      - name: catalogue
        image: 834725375088.dkr.ecr.us-east-1.amazonaws.com/catalogue:8.0.0
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef:
              name: catalogue-configmap

--- 

apiVersion: v1
kind: Service
metadata:
  name: catalogue-svc
spec:
  selector:
   app: catalogue
  ports:
    - protocol: TCP
      port: 8080              # Port number of the service that it has to listen on 
      targetPort: 8080        # Port number of the container that it has to forward to

--- 

apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue-configmap
data:
  MONGO_URL: "mongodb://admin1:roboshop1@robot-dev-docdb.cluster-ciqb6xvrbz0q.us-east-1.docdb.amazonaws.com:27017/catalogue?tls=true&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false"  

--- 

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: catalogue-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: catalogue
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75